### ISSUE TITLE
Simplify help output for run/update

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#1358]
Right now, run and update have a lot of flags (see collapsed section)
<details>
<summary>Click here to see current help output</summary>

```
$ acorn run --help
Run an app from an image or Acornfile

Usage:
  acorn run [flags] IMAGE|DIRECTORY [acorn args]

Examples:
# Publish and Expose Port Syntax
  # Publish port 80 for any containers that define it as a port
  acorn run -p 80 .

  # Publish container "myapp" using the hostname app.example.com
  acorn run --publish app.example.com:myapp .

  # Expose port 80 to the rest of the cluster as port 8080
  acorn run --expose 8080:80/http .

# Labels and Annotations Syntax
  # Add a label to all resources created by the app
  acorn run --label key=value .

  # Add a label to resources created for all containers
  acorn run --label containers:key=value .

  # Add a label to the resources created for the volume named "myvolume"
  acorn run --label volumes:myvolume:key=value .

# Link Syntax
  # Link the running acorn application named "mydatabase" into the current app, replacing the container named "db"
  acorn run --link mydatabase:db .

# Secret Syntax
  # Bind the acorn secret named "mycredentials" into the current app, replacing the secret named "creds". See "acorn secrets --help" for more info
  acorn run --secret mycredentials:creds .

# Volume Syntax
  # Create the volume named "mydata" with a size of 5 gigabyes and using the "fast" storage class
  acorn run --volume mydata,size=5G,class=fast .

  # Bind the acorn volume named "mydata" into the current app, replacing the volume named "data", See "acorn volumes --help for more info"
  acorn run --volume mydata:data .

# Automatic upgrades
  # Automatic upgrade for an app will be enabled if '#', '*', or '**' appears in the image's tag. Tags will sorted according to the rules for these special characters described below. The newest tag will be selected for upgrade.

  # '#' denotes a segment of the image tag that should be sorted numerically when finding the newest tag.
  # This example deploys the hello-world app with auto-upgrade enabled and matching all major, minor, and patch versions:
  acorn run myorg/hello-world:v#.#.#

  # '*' denotes a segment of the image tag that should sorted alphabetically when finding the latest tag.
  # In this example, if you had a tag named alpha and a tag named zeta, zeta would be recognized as the newest:
  acorn run myorg/hello-world:*

  # '**' denotes a wildcard. This segment of the image tag won't be considered when sorting. This is useful if your tags have a segment that is unpredictable.
  # This example would sort numerically according to major and minor version (ie v1.2) and ignore anything following the "-":
  acorn run myorg/hello-world:v#.#-**

  # NOTE: Depending on your shell, you may see errors when using '*' and '**'. Using quotes will tell the shell to ignore them so Acorn can parse them:
  acorn run "myorg/hello-world:v#.#-**"

  # Automatic upgrades can be configured explicitly via a flag.
  # In this example, the tag will always be "latest", but acorn will periodically check to see if new content has been pushed to that tag:
  acorn run --auto-upgrade myorg/hello-world:latest

  # To have acorn notify you that an app has an upgrade available and require confirmation before proceeding, set the notify-upgrade flag:
  acorn run --notify-upgrade myorg/hello-world:v#.#.# myapp
  # To proceed with an upgrade you've been notified of:
  acorn update --confirm-upgrade myapp


Flags:
      --annotation strings        Add annotations to the app and the resources it creates (format [type:][name:]key=value) (ex k=v, containers:k=v)
      --auto-upgrade              Enabled automatic upgrades.
  -b, --bidirectional-sync        In interactive mode download changes in addition to uploading
      --compute-class strings     Set computeclass for a workload in the format of workload=computeclass. Specify a single computeclass to set all workloads. (ex foo=example-class or example-class)
  -i, --dev                       Enable interactive dev mode: build image, stream logs/status in the foreground and stop on exit
  -e, --env strings               Environment variables to set on running containers
  -f, --file string               Name of the build file (default "DIRECTORY/Acornfile")
  -h, --help                      help for run
      --interval string           If configured for auto-upgrade, this is the time interval at which to check for new releases (ex: 1h, 5m)
  -l, --label strings             Add labels to the app and the resources it creates (format [type:][name:]key=value) (ex k=v, containers:k=v)
      --link strings              Link external app as a service in the current app (format app-name:container-name)
  -m, --memory strings            Set memory for a workload in the format of workload=memory. Only specify an amount to set all workloads. (ex foo=512Mi or 512Mi)
  -n, --name string               Name of app to create
      --notify-upgrade            If true and the app is configured for auto-upgrades, you will be notified in the CLI when an upgrade is available and must confirm it
  -o, --output string             Output API request without creating app (json, yaml)
      --profile strings           Profile to assign default values
  -p, --publish strings           Publish port of application (format [public:]private) (ex 81:80)
  -P, --publish-all               Publish all (true) or none (false) of the defined ports of application
  -q, --quiet                     Do not print status
  -s, --secret strings            Bind an existing secret (format existing:sec-name) (ex: sec-name:app-secret)
      --target-namespace string   The name of the namespace to be created and deleted for the application resources
  -u, --update                    Update the app if it already exists
  -v, --volume stringArray        Bind an existing volume (format existing:vol-name,field=value) (ex: pvc-name:app-data)
      --wait                      Wait for app to become ready before command exiting (default true)

Global Flags:
  -A, --all-projects        Use all known projects
      --debug               Enable debug logging
      --debug-level int     Debug log level (valid 0-9) (default 7)
      --kubeconfig string   Explicitly use kubeconfig file, overriding current project
  -j, --project string      Project to work in
```
</details>

We want to simplify and reduce this. We want to encourage users to define as much of their deployment as possible in the acorn file and just use profile flags to, well, change profiles. So, we want to hide all the flags that correspond to runtime overrides of the acornfile. We want the help text to just have the bare minimum flags.

It's important to note that we just want to hide these flags, not actually delete them. We also want to POSSIBLY introduce a new `acorn help run|update|whatever flag` and have the more detailed help information there. But I'm not sure about this, so we should talk about it before implementing

Here's my current breakdown:

### Keep (I think)
```
  -f, --file
  -h, --help
  -n, --name
  -o, --output
      --profile
  -q, --quiet
      --wait
```

### Hide
```
      --annotation
      --compute-class strings
  -e, --env
  -l, --label
      --link
  -m, --memory
  -p, --publish
  -P, --publish-all
  -s, --secret
      --target-namespace
  -u, --update
  -v, --volume
```

### Unsure
`acorn dev` is becoming a new top level command. I guess -b would be a flag on it
```
  -i, --dev
  -b, --bidirectional-sync
```

Not sure if the auto-upgrade related flags make sense to be exposed in the Acornfile or not
```
      --auto-upgrade
      --interval string
      --notify-upgrade
```

**Comment by sangee2004** [comment]
Tested with acorn version v0.7.0-alpha1-35-g1fc80f7d+1fc80f7d

`acorn run --help` shows the following options for Flags:

```
Flags:
      --auto-upgrade      Enabled automatic upgrades.
  -f, --file string       Name of the build file (default "DIRECTORY/Acornfile")
  -h, --help              help for run
      --help-advanced     Show verbose help text
  -n, --name string       Name of app to create
      --notify-upgrade    If true and the app is configured for auto-upgrades, you will be notified in the CLI when an upgrade is available and must confirm it
  -o, --output string     Output API request without creating app (json, yaml)
      --profile strings   Profile to assign default values
  -q, --quiet             Do not print status
      --replace           Replace the app with only defined values, resetting undefined fields to default values
  -u, --update            Update the app if it already exists
      --wait              Wait for app to become ready before command exiting (default: true)

```

`acorn run --help-advanced` --> shows all the options.

Had few follow up questions/confirmations

1. ` --help-advanced` includes these 2 options .Can they be removed completely from `acorn run` since we have support for `acorn dev` now ?

```
  -i, --dev                       Enable interactive dev mode: build image, stream logs/status in the foreground and stop on exit
  -b, --bidirectional-sync        In interactive mode download changes in addition to uploading
```

2.  Regarding ` --link` , `-s` and `-v` (when used for binding) which are presented in `--advanced-help` , should we consider moving them to `--help` since these actions cannot be achieved from within Acornfile.

**Comment by cjellick** [comment]
>  --help-advanced includes these 2 options .Can they be removed completely from acorn run since we have support for acorn dev now ?

Yes, lets do that

> Regarding  --link , -s and -v (when used for binding) which are presented in --advanced-help , should we consider moving them to --help since these actions cannot be achieved from within Acornfile.

Let's keep the in advanced help for now. @ibuildthecloud has a vision of hiding complex argument combinations behind profiles primarily. Let's see if this works out or not.

> Regarding acorn update  --help, there are lot of things broken:

Yeah, seems like all these things should be fixed

**Comment by g-linville** [comment]
@cjellick a question. Currently, all arguments available to `acorn run` are also available to `acorn update` since it ultimately calls the function for `acorn run` after processing the arguments. So I can hide the option `-n` from `acorn update --help` and `acorn update --help-advanced`, but unless we want to totally decouple `acorn update` from `acorn run`, I can't take it completely away.

This is because the struct that defines all the fields for `acorn update` includes the `RunArgs` struct.

However, I am a little confused why we want to remove `-n` as an option from `acorn update` because, looking at the logic for `acorn run --update`, `--name` is a required argument. And this same logic is what eventually runs for `acorn update`.

**Comment by cjellick** [comment]
dont remove the name option. just make the update help match the run help

dont functionally change the cli commands at all

**Comment by g-linville** [comment]
Merged to main.

**Comment by sangee2004** [comment]
Tested with acorn version v0.7.0-alpha1-148-g7909ed41+7909ed41

`acorn run --help-advanced` does not include "-i' and "-b" options.

`acorn update --help-advanced` is now available to list all the flags that can be used with `acorn update`

`acorn update --help` lists `--image` option.

"--replace" option is not listed in `acorn update --help` anymore.

@g-linville @cjellick I still see the "-n" option available in `acorn update --help` lists . Having this option made available for `acorn update` is confusing. AFAIK this option should not used by `acorn update` and it should use only `APP_NAME`  which is a required parameter.

**Comment by g-linville** [comment]
Removed `-n/--name` from `acorn update`.

**Comment by sangee2004** [comment]
Tested with `acorn version v0.7.0-alpha1-163-g7882f4c1+7882f4c1`

`-n/--name` option is not presented in `acorn update --help`
