### ISSUE TITLE
Hitting rate limits when testing with imageAllowRules.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1414]
acorn version v0.6.0-98-g871782ee+871782ee

Steps to reproduce the problem:
I had been deploying few apps in projects that have imageAllowRules. 
Images are from docker hub.
After some attempts , i start seeing rate limits .
I have seen this happen twice so far with using 2 different authenticated dockerhub users.

**Comment by sangee2004** [comment]
@iwilltry42  When apps get deployed in a project with imageAllowRule , is there a constant check made for the images ? If so, how often is this done?
I am already rate limited in my setup that was fresh from about 1 hour back, so 100 pulls consumed . I barely have 3 -4 apps running out of which 1 of them is auto-upgrade format.
May be the autoupgrade is making this happen so fast. But wanted to know if regular images (no autoupgrade) is also doing any images pulls at regular intervals ?

**Comment by sangee2004** [comment]
acorn version v0.6.0-106-g09f636a2+09f636a2

I am still hitting ratelimit issues when testing with  imageAllowRules.
Would deploying apps with `auto-upgrade` tag and public images hosted in docker ( I am not using private images in docker hub) result in ratelimit issues ?

I had about 3-4 apps running with images  in auto-upgrade format with --interval set to 15s before I hit rate-limit issue.

```
acorn apps -j acorn
NAME                     IMAGE                                                                                      HEALTHY   UP-TO-DATE   CREATED     ENDPOINTS                                                                    MESSAGE
check1                   index.docker.io/sangeetha/myfirstacorn:v6.0.0                                              1         1            18m ago     http://nginx1-check1-762ea864.local.on-acorn.io => nginx1:80                 [image-pull: GET https://index.docker.io/v2/sangeetha/myfirstacorn/manifests/v6.0.0: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit]
mytestauto1              index.docker.io/sangeetha/testautoupgradedeploy1:v0.0.2                                    1         1            19m ago     http://nginx-mytestauto1-fe277915.local.on-acorn.io => nginx:80              [image-pull: GET https://index.docker.io/v2/sangeetha/testautoupgradedeploy1/manifests/v0.0.2: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit]
mytestauto                                                                                                          0         0            20m ago                                                                                  [image-allowed: waiting for image to satisfy auto-upgrade tag v#.#.#] [image-pull: waiting for image to satisfy auto-upgrade tag v#.#.#]
testautoupgradedeploy1   index.docker.io/sangeetha/testautoupgradedeploy1:v0.0.2                                    1         1            21m ago     http://nginx-testautoupgradedeploy1-750c70b1.local.on-acorn.io => nginx:80   [image-pull: GET https://index.docker.io/v2/sangeetha/testautoupgradedeploy1/manifests/v0.0.2: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit]
```

**Comment by iwilltry42** [comment]
@sangee2004 I did more thorough debugging now.
The check for 404s returned by the initial HEAD request failed.
I fixed that locally, but I also see the second error you get there on image-pull.. though that's probably unrelated to imageAllowRules :thinking:

**Comment by iwilltry42** [comment]
Here we go again @sangee2004 ! 
I'm sorry for this back and forth. Seems like the Debugger and Network inspection betrayed me last time :roll_eyes:

**Comment by sangee2004** [comment]
@iwilltry42 I fixed that locally, but I also see the second error you get there on image-pull.. though that's probably unrelated to imageAllowRules ==> This was an app that was deployed with autoupgrade tag were there is no matching tags that are signed. Thats the only difference between the 2 apps that were deployed. The first one had few matching tags that satified the imageAllowRules but the 2nd app has none.

**Comment by sangee2004** [comment]
Tested with acorn version `v0.6.0-132-gdc73d55a+dc73d55a`


Remaining pulls - 84 @ ~1:22 PM

Remaining pulls -  66. @ ~1:26 PM

Remaining pulls - 38: @ ~1:34 PM

I am still seeing the docker rate-limit being consumed steadily when testing when deploying apps in autoupgrade format in projects that have imageRuleAllow:

These are the 2 apps I have running with 15s interval in auto-upgrade format:

```
 acorn apps
NAME      IMAGE                                           HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS                                                       MESSAGE
mytest2   index.docker.io/sangeetha/mydeletecheck         1         1            12m ago   http://myweb1-mytest2-75092b32.local.on-acorn.io => myweb1:80   [image-allowed: failed to check if image is allowed: error ensuring references for image index.docker.io/sangeetha/mydeletecheck: failed to ensure signature artifact: no matching signatures: expected signature artifact index.docker.io/sangeetha/mydeletecheck:sha256-47a8d83df3aef36b48a15415549e6487ddb94075c77e0d7f33894685e8bcce4e.sig not found]
mytest1   index.docker.io/sangeetha/myfirstacorn:v0.0.2   2         2            13m ago   http://nginx-mytest1-6ee78f86.local.on-acorn.io => nginx:80     OK
```

**Comment by sangee2004** [comment]
I see the same behavior of docker rate-limit being consumed steadily when  deploying apps in autoupgrade format in projects that have  **NO** imageRuleAllow.

This issue is tracked in - https://github.com/acorn-io/acorn/issues/1398

**Comment by sangee2004** [comment]
I will leave this in open state until https://github.com/acorn-io/acorn/issues/1398 gets addressed and try these usecases as well.

**Comment by sangee2004** [comment]
Tested with `acorn version v0.6.0-136-gc2c4989d+c2c4989d`

Did not encounter Rate limit issues when testing the following apps:

1. Apps deployed in autoupgrade format with --interval=15s  for public images hosted in docker hub
2. Apps deployed in autoupgrade format with --interval=15s  for private images hosted in docker hub
3. Apps deployed in autoupgrade format with --interval=15s  for public images hosted in docker hub in projects that have ImageAllowRules.
4. Apps deployed in autoupgrade format with --interval=15s  for public images hosted in docker hub in projects that have ImageAllowRules and dont have any version that matches the ImageAllowRules.

**Comment by iwilltry42** [comment]
This is the best thing I've read in a while, thank you 😁
