### ISSUE TITLE
Services - There is no schema validation done on generated services and secrets.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1585]
acorn version v0.7.0-alpha1-39-g696e7f52+696e7f52

Steps to reproduce the problem:

Deploy an acorn which has  generated services and secrets.

```
services: "secret-getter": {
  generated: job: "create-secret"
}

jobs: "create-secret": {
  image: "ubuntu"
  files: "/create.sh": """
  #!/bin/sh
  set -x
  cat > /run/secrets/output<<EOF
  service: "secret-getter": {  ==> typo here ..should have been services
      secrets: ["output"]
   }
   secrets: "output": {
     type: "opaque"
     data:
        key1: "value"           ==> Error here ..missing {}
        key2: "value2"
   }
  """
  entrypoint: ["/create.sh"]
}

secrets: output: {
  type: "generated"
  params: job: "create-secret"
}
```
Try to launch app using the above acorn.
App deployment succeeds and there is no indication that the service was created with invalid syntax.

Expected Behavior:
App deployment should fail in this case with error message indicating the schema errors in  generated services and secrets.

Build an image using this Acornfile and consume this as a service 
```
 cat AcornfileEnv
containers: {
  nginx: {
    image: "nginx"
    env: {
     "SECRET": "@{secrets.mysec.output.key1}"
}
}
}
services: {
     mysec: image: "<service Image>"
}
```
App gets deployed successfully. But the environment variable does not get set as expected since the service had errors.
```
 % acorn apps
NAME           IMAGE          HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS   MESSAGE
mytest.mysec   493dd83e8bfb   0         0            8s ago                OK
mytest         d8f93fd97495   1         1            9s ago                OK
% acorn secrets
NAME                  TYPE        KEYS        CREATED
mytest.mysec.output   generated   [content]   10s ago
```

Expected Behavior:
App deployment should fail in this case with error message indicating the schema errors in  generated services and secrets.

**Comment by cjellick** [comment]
theres a chance that this one is addressed by https://github.com/acorn-io/acorn/pull/1763/files

**Comment by sangee2004** [comment]
Tested with acorn version `v0.7.0-38-gdc95c02b+dc95c02b`


1. When deploying app with the invalid schema in Acornfile containing generated  service and secret.

App fails to deploy successfully with parsing errors as expected:

```
acorn apps
NAME                IMAGE          HEALTHY   UP-TO-DATE   CREATED    ENDPOINTS   MESSAGE
mytestserviceinco   7c355c8e7376   0         0            104s ago               [defined: failed to parse generated output for service [secret-getter] bytes [148]: field not allowed: service:
    /_internal_/schema/v1/app.cue:355:7
    Acornfile:1:1
] [services: secret-getter: [pending create]] [secrets: output: [pending create]] [controller: [routes.go:76] failed to parse generated output for service [secret-getter] bytes [148]: field not allowed: service:
    /_internal_/schema/v1/app.cue:355:7
    Acornfile:1:1
]
```

Once this parsing error was corrected and app was deployed with still having issues with generated secrets, app fails with following error message:

```
acorn apps
NAME                IMAGE          HEALTHY   UP-TO-DATE   CREATED     ENDPOINTS   MESSAGE
mytestserviceinco   6d9ca68291fe   0         0            3m36s ago               [defined: failed to parse generated output for service [secret-getter] bytes [149]: secrets.output: 5 errors in empty disjunction:
secrets.output: field not allowed: key2:
    /_internal_/schema/v1/app.cue:227:14
    /_internal_/schema/v1/app.cue:234:16
    /_internal_/schema/v1/app.cue:235:2
    /_internal_/schema/v1/app.cue:280:11
    /_internal_/schema/v1/app.cue:355:7
    /_internal_/schema/v1/app.cue:363:28
    Acornfile:8:7
secrets.output.type: conflicting values "basic" and "opaque":
    /_internal_/schema/v1/app.cue:263:8
    /_internal_/schema/v1/app.cue:280:27
    /_internal_/schema/v1/app.cue:363:28
    Acornfile:5:10
secrets.output.type: conflicting values "generated" and "opaque":
    /_internal_/schema/v1/app.cue:272:8
    /_internal_/schema/v1/app.cue:280:46
    /_internal_/schema/v1/app.cue:363:28
    Acornfile:5:10
secrets.output.type: conflicting values "template" and "opaque":
    /_internal_/schema/v1/app.cue:243:8
    /_internal_/schema/v1/app.cue:280:65
    /_internal_/schema/v1/app.cue:363:28
    Acornfile:5:10
secrets.output.type: conflicting values "token" and "opaque":
    /_internal_/schema/v1/app.cue:249:8
    /_internal_/schema/v1/app.cue:280:83
    /_internal_/schema/v1/app.cue:363:28
    Acornfile:5:10
] [services: secret-getter: [pending create]] [secrets: output: [pending create]] [controller: [routes.go:76] failed to parse generated output for service [secret-getter] bytes [149]: secrets.output: 5 errors in empty disjunction:
secrets.output: field not allowed: key2:
    /_internal_/schema/v1/app.cue:227:14
    /_internal_/schema/v1/app.cue:234:16
    /_internal_/schema/v1/app.cue:235:2
    /_internal_/schema/v1/app.cue:280:11
    /_internal_/schema/v1/app.cue:355:7
    /_internal_/schema/v1/app.cue:363:28
    Acornfile:8:7
secrets.output.type: conflicting values "basic" and "opaque":
    /_internal_/schema/v1/app.cue:263:8
    /_internal_/schema/v1/app.cue:280:27
    /_internal_/schema/v1/app.cue:363:28
    Acornfile:5:10
secrets.output.type: conflicting values "generated" and "opaque":
    /_internal_/schema/v1/app.cue:272:8
    /_internal_/schema/v1/app.cue:280:46
    /_internal_/schema/v1/app.cue:363:28
    Acornfile:5:10
secrets.output.type: conflicting values "template" and "opaque":
    /_internal_/schema/v1/app.cue:243:8
    /_internal_/schema/v1/app.cue:280:65
    /_internal_/schema/v1/app.cue:363:28
    Acornfile:5:10
secrets.output.type: conflicting values "token" and "opaque":
    /_internal_/schema/v1/app.cue:249:8
    /_internal_/schema/v1/app.cue:280:83
    /_internal_/schema/v1/app.cue:363:28
    Acornfile:5:10
]
```


2. When deploying apps with service image that was built from incorrect Acornfile , app fails to deploy successfully as expected.

```
acorn apps
NAME            IMAGE          HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS   MESSAGE
mytest1         b47fa7e28d3b   0         0            44s ago               [containers: nginx: [error in expression [secrets.mysec.output.key1]: secret [mysec.output] not found]] [services: mysec: [is not ready]]
mytest1.mysec   7c355c8e7376   0         0            44s ago               [defined: failed to parse generated output for service [secret-getter] bytes [148]: field not allowed: service:
    /_internal_/schema/v1/app.cue:355:7
    Acornfile:1:1
] [services: secret-getter: [pending create]] [secrets: output: [pending create]] [controller: [routes.go:76] failed to parse generated output for service [secret-getter] bytes [148]: field not allowed: service:
    /_internal_/schema/v1/app.cue:355:7
    Acornfile:1:1
]
```
