### ISSUE TITLE
Problems working with local and remote images with the same digests

### ISSUE THREAD

**Issue by g-linville** [acorn-io/acorn#1662]
### Overview

I've noticed three strange things that can happen when working with the same images tagged locally and remotely in the same Acorn project. These three problems are:

- Duplicate output appears in the `acorn image` command due to similar but slightly different tags on the same image.
- Existing tags are wrongfully removed from an image when another tag on the same image is updated to a newer version of the image.
- When a single image digest is referred to by both remote (i.e. `index.docker.io/foo/bar:latest`) and local (i.e. `local:latest`) tags, and you remove the remote tag, the local tag becomes unusable.

### Repro steps

Here is a walkthrough of how to reproduce all three bugs. Tested on the main branch at commit sha `a614cb3`.

1. Install Acorn
2. Create a second project: `acorn project create two`
3. Log in to Docker Hub in project two: `acorn login -j two index.docker.io`
4. Build and push a brand new image up to Docker Hub using project two. I'm providing my own Acornfile and repo name example here; tweak it to your needs.
   ```
   $ cat Acornfile
   containers: nginx: {
	image: "nginx:latest"
	ports: "80/http"
	files: "/usr/share/nginx/html/index.html": "Version 1"
   }
   $ acorn build -t docker.io/grantlinville/upgradetest:latest --push -j two .
   ```
5. Run an app with this remote image: `acorn run -n upgradetest --auto-upgrade docker.io/grantlinville/upgradetest:latest`
6. Build the same image again with the same Acornfile, this time in the `acorn` project: `acorn build -t localversion:latest .`
7. Run `acorn image` and observe the output. Already you can see the duplication, the first bug I listed:
   ```
   $ acorn image
   REPOSITORY                                  TAG       IMAGE-ID
   index.docker.io/grantlinville/upgradetest   latest    523c854dee92
   index.docker.io/grantlinville/upgradetest   latest    523c854dee92
   localversion                                latest    523c854dee92
   ```
   - Note: if you look at the ImageInstance in detail, you can see that it has tags for both `docker.io` and `index.docker.io`, which is likely what is causing this:
     ```yaml
     apiVersion: internal.acorn.io/v1
     digest: sha256:523c854dee926208a3f63c81a55643425d09e15ff40492843f6a87dbaf62882b
     kind: ImageInstance
     metadata:
       creationTimestamp: "2023-05-25T16:55:42Z"
       generation: 3
       name: 523c854dee926208a3f63c81a55643425d09e15ff40492843f6a87dbaf62882b
       namespace: acorn
       resourceVersion: "1022"
       uid: 7b6ba364-48ab-4767-b0d6-c9fcf665e598
     remote: true
     repo: index.docker.io/grantlinville/upgradetest
     tags:
     - docker.io/grantlinville/upgradetest:latest
     - index.docker.io/grantlinville/upgradetest:latest
     - localversion:latest
     ```
8. Update the Acornfile to change just the version number in the index file:
   ```
   $ cat Acornfile
   containers: nginx: {
	image: "nginx:latest"
	ports: "80/http"
	files: "/usr/share/nginx/html/index.html": "Version 2"
   }
   ```
9. Build and push this new version to Docker Hub, again from project two: `acorn build -t docker.io/grantlinville/upgradetest:latest --push -j two .`
10. Run `acorn pull docker.io/grantlinville/upgradetest:latest`
11. Run `acorn image` and observe that the `localversion:latest` tag is now totally gone. This is the second bug I listed.
    ```
    $ acorn image
    REPOSITORY                                  TAG       IMAGE-ID
    index.docker.io/grantlinville/upgradetest   latest    231433df6dd0
    index.docker.io/grantlinville/upgradetest   latest    523c854dee92
    index.docker.io/grantlinville/upgradetest   latest    523c854dee92
    ```
12. Delete the upgradetest app: `acorn rm upgradetest`
13. Delete all of your images from the `acorn` project: `acorn image -a | grep -v REPO | awk '{print $3}' | xargs acorn image rm -f`
14. Run the upgradetest app again, using the remote image from Docker Hub: `acorn run -n upgradetest --auto-upgrade docker.io/grantlinville/upgradetest:latest`
15. Build the localversion again without modifying the Acornfile: `acorn build -t localversion:latest .`
16. Run `acorn image` and see that both images have the same Image ID:
    ```
    $ acorn image
    REPOSITORY                                  TAG       IMAGE-ID
    index.docker.io/grantlinville/upgradetest   latest    d2ce031e4119
    index.docker.io/grantlinville/upgradetest   latest    d2ce031e4119
    localversion                                latest    d2ce031e4119
    ```
17. Delete the upgradetest app again: `acorn rm upgradetest`
18. Delete the upgradetest image locally in the `acorn` project: `acorn image rm docker.io/grantlinville/upgradetest:latest`
19. Run the same command again, since the image was listed twice.
20. Run `acorn image` and verify that `localversion:latest` is still there:
    ```
    $ acorn image
    REPOSITORY     TAG       IMAGE-ID
    localversion   latest    d2ce031e4119
    ```
21. Attempt to run an app with `localversion:latest`: `acorn run -n localversion localversion:latest`
22. Observe that the app fails to start because Acorn tries to pull the image from Docker Hub, where it doesn't exist: `STATUS: ENDPOINTS[] HEALTHY[0] UPTODATE[0] [image-pull: GET https://index.docker.io/v2/library/localversion/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/localversion Type:repository]]]`

#### Duplicate output bug

I believe this one is caused by the difference between building an image with the tag `docker.io/.*` locally and pulling one implicitly by running an app from an image in Docker Hub. When building it locally, the tag that gets created on the ImageInstance starts with `index.docker.io`. But when pulling implicitly by running an app using a remote image, the tag on the ImageInstance starts with `docker.io`. If we make these consistent, I think that will fix this bug.

#### Existing tags wrongfully removed bug

Not really sure what is causing this one. Probably just a logic error somewhere in a function that is responsible for removing tags from other images when a newer image gets a new tag.

#### Local tag becomes unusable after removing remote tag

Some ImageInstances are marked with `Remote: true`. This happens when they are created for AppInstances that are utilizing remote images, not ones built locally. I think we need to add some logic that detects when a new image is built locally and a new tag is created on the same ImageInstance, we know that that ImageInstance is now local, and `Remote` should be set to `false`. There are probably some other things that we need to be looking out for as well.

**Comment by cjellick** [comment]
Addressing the beahviors:

> Duplicate output appears in the acorn image command due to similar but slightly different tags on the same image.

is captured here: https://github.com/acorn-io/acorn/issues/1502 and being addressed by @thedadams 


> Existing tags are wrongfully removed from an image when another tag on the same image is updated to a newer version of the image.

Yeah, legit bug. To be clear, the crux of this bug is that a completely independent image tag was nuked as a side effect


> When a single image digest is referred to by both remote (i.e. index.docker.io/foo/bar:latest) and local (i.e. local:latest) tags, and you remove the remote tag, the local tag becomes unusable.

Yeah, legit.

**Comment by thedadams** [comment]
I am testing the changes in #1502 with the steps laid out above.

After step 7, I no longer see the duplicate tags:
```
REPOSITORY                              TAG       IMAGE-ID
index.docker.io/thedadams/upgradetest   latest    e16b2e9c793c
localversion                            latest    e16b2e9c793c
```
Additionally, the `ImageInstance` also looks as expected:
```
apiVersion: internal.acorn.io/v1
digest: sha256:e16b2e9c793cdbfd95453366885a92672f46a70a10cc5667b36f5b81b1edde34
kind: ImageInstance
metadata:
  creationTimestamp: "2023-06-06T15:21:21Z"
  generation: 2
  name: e16b2e9c793cdbfd95453366885a92672f46a70a10cc5667b36f5b81b1edde34
  namespace: acorn
  resourceVersion: "3302"
  uid: a648d2ad-099e-442b-9c91-3cf4332a05e9
remote: true
repo: index.docker.io/thedadams/upgradetest
tags:
- index.docker.io/thedadams/upgradetest:latest
- localversion:latest
```

After step 11, the `localversion` tag still exists:
```
REPOSITORY                              TAG       IMAGE-ID
localversion                            latest    e16b2e9c793c
index.docker.io/thedadams/upgradetest   latest    9d3003161cb2
```

Stating for completeness, but, of course, after step 16, I don't see duplicate tags:
```
REPOSITORY                              TAG       IMAGE-ID
index.docker.io/thedadams/upgradetest   latest    9d3003161cb2
localversion                            latest    9d3003161cb2
```

After step 22, I still see the `UNAUTHORIZED` error.

I will investigate the `UNAUTHORIZED` error and submit a separate change.

**Comment by thedadams** [comment]
This issue is being used to track the `UNAUTHORIZED` error. The other issues contained here are being handled by #1502.

So, to verify this, I believe these are the steps:
1. Create a new project, say `two`: `acorn project create two`
2. Log into `docker.io` in this new project: `acorn -j two login docker.io`
3. In this new project build and push an image: `acorn -j build -t index.docker.io/thedadams/myapp:latest --push .`
4. Run an app in the `acorn` project: `acorn run index.docker.io/thedadams/myapp:latest`
5. Build this same image in the `acorn` project: `acorn build -t localversion:latest .`
It is imperative that this image has the same image ID as the built and pushed one.
6. Remove the app created in step 4.
7. Remove the tag: `acorn image rm index.docker.io/thedadams/myapp:latest`
8. Run an app with the locally built version: `acorn run localversion:latest`

Previously, after step 8, you would get an `UNAUTHORIZED` error as above in the description. This should no longer be the case with the latest changes and the app should come up successfully.

**Comment by sangee2004** [comment]
Tested with `acorn version v0.7.0-alpha1-163-g7882f4c1+7882f4c1`

Followed the steps in - https://github.com/acorn-io/acorn/issues/1662#issuecomment-1581217271 .

I am able to deploy app successfully using the locally built version.

**Comment by sangee2004** [comment]
Tested with acorn version v0.7.0-alpha1-168-g5dc719d0+5dc719d0

Followed all the steps from bug report and I am not able to reproduce the issues.


- In Step 7 —> There are no duplicates 

acorn images
REPOSITORY                               TAG       IMAGE-ID
index.docker.io/sangeetha/myfirstacorn   latest    76bad608b788
localversion                             latest    76bad608b788

- In Step 11 -> local tag is not getting deleted after `acorn pull`

```
acorn images
REPOSITORY                               TAG       IMAGE-ID
index.docker.io/sangeetha/myfirstacorn   latest    a431e2f53f97
localversion                             latest    a431e2f53f97
```
 
After `acorn pull docker.io/sangeetha/myfirstacorn `

To:
```
acorn images
REPOSITORY                               TAG       IMAGE-ID
localversion                             latest    a431e2f53f97
index.docker.io/sangeetha/myfirstacorn   latest    6af45eb81e57
```

- In Step22 -> App deployment succeeds
